### ISSUE TITLE
hi i have question

### ISSUE THREAD

**Issue by jst7501** [three11/react-template-ts#2240]
I am a student studying React.
When I build, only a white screen appears.
Uncaught TypeError: Cannot read properties of undefined (reading 'use')
    at 836350 (main.a172be022226d07286ba.bundle.js:205:1331950)
    at i (runtime~main.b6fd63f9092825e4c911.bundle.js:1:147)
    at 100036 (main.a172be022226d07286ba.bundle.js:205:1336908)
    at i (runtime~main.b6fd63f9092825e4c911.bundle.js:1:147)
    at 827750 (main.a172be022226d07286ba.bundle.js:205:1341900)
    at i (runtime~main.b6fd63f9092825e4c911.bundle.js:1:147)
    at 969535 (main.a172be022226d07286ba.bundle.js:205:1341217)
    at i (runtime~main.b6fd63f9092825e4c911.bundle.js:1:147)
    at 398758 (main.a172be022226d07286ba.bundle.js:205:1332438)
    at i (runtime~main.b6fd63f9092825e4c911.bundle.js:1:147)

i don't know why i have this problem

**Comment by jst7501** [comment]
Even if you try to build a new clone I get the same error

**Comment by scriptex** [comment]
That's really weird. I just pushed a quick fix for the way the supported locales are being used and imported but this shouldn't cause your issue.
Can you please try using Node v18? 
Also, which OS are you using? I am using MacOS and Ubuntu and it works on both...

**Comment by jst7501** [comment]
I am also using m1 and node18 No matter how much I searched, I couldn't fix the error. thanks for the help
I'm building I tested it using npx serve. Is something wrong?

**Comment by scriptex** [comment]
I think I figured it out. Can you please check again but using the latest version? I just released 1.10.2 to NPM and Github.

**Comment by jst7501** [comment]
yes i will try it tomorrow I'm Korean so it's night now thank you

**Comment by jst7501** [comment]
A friend of mine tried it and it worked I think there is a problem with i18n
![Uploading ABCFB08C-52B3-4E78-9DE1-5CAF90010131.png…]()

**Comment by scriptex** [comment]
It was a misconfiguration in the Typescript config file. It should be fixed now. Please use the most recent version either from NPM or by downloading the release files from Github.

**Comment by jst7501** [comment]
The issue has been resolved thank you !!!!!!!!

**Comment by scriptex** [comment]
I am happy I was able to help you :) Thanks for finding it.
